Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20

Style/GuardClause:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/ClassLength:
  Max: 120
